name: swift-jni ci
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '45 3,15 * * *'
jobs:
  linux-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Test Swift Package Linux"
        run: SWIFT_JAVA_JNI_CORE=0 swift test
      - name: "Test Swift Package Linux (SWIFT_JAVA_JNI_CORE)"
        run: SWIFT_JAVA_JNI_CORE=1 swift test
      - name: "Test Swift Package Android"
        uses: skiptools/swift-android-action@v2
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Test Swift Package macOS"
        run: SWIFT_JAVA_JNI_CORE=0 swift test
      - name: "Test Swift Package macOS (SWIFT_JAVA_JNI_CORE)"
        run: SWIFT_JAVA_JNI_CORE=1 swift test

