name: swift-java ci
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '45 3,15 * * *'
jobs:
  linux-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package Linux"
        run: swift test
      - name: "Test Swift Package Android"
        if: false # issues with JNI_CreateJavaVM on Android
        uses: skiptools/swift-android-action@v2
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Test Swift Package macOS"
        run: swift test
  windows:
    runs-on: windows-latest
    if: false # not yet working, needs dlopen, dlsym, etc.
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.1
          tag: 6.1-RELEASE
      - uses: actions/checkout@v4
      - run: swift test

